# Generated by Django 4.2.19 on 2025-02-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscanner', '0002_scanrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_value',
            field=models.IntegerField(default=1),
        ),
    ]
