# Generated by Django 4.2.19 on 2025-03-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingame", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="item_image",
            field=models.ImageField(blank=True, null=True, upload_to="bingame/items/"),
        ),
    ]
