# Generated by Django 4.2.19 on 2025-02-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingame', '0002_populate_bins_and_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BinLeaderboardEntry',
        ),
    ]
