# Generated by Django 4.2.19 on 2025-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingame', '0002_populate_bins_and_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinLeaderboard',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_score', models.IntegerField()),
            ],
        ),
    ]
