# Generated by Django 4.2.19 on 2025-03-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='forum_points',
            field=models.IntegerField(default=0),
        ),
    ]
