# Generated by Django 4.2.19 on 2025-03-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopItems',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='static/img/shop/')),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
    ]
