# Generated by Django 4.2.19 on 2025-03-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItems',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/')),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
    ]
