# Generated by Django 4.2.19 on 2025-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='aesthetic_appeal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitems',
            name='carbon_uptake',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopitems',
            name='habitat',
            field=models.IntegerField(default=0),
        ),
    ]
