# Generated by Django 4.2.19 on 2025-02-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderboardEntry',
        ),
    ]
